void-linux/void-mklive

- build-x86-images.sh.in
All isos that use X_PKGS contain already the package for the amd microcode.
> build-x86-images.sh: Add intel-ucode to X_PKGS.

- mklive.sh.in
After https://github.com/void-linux/void-packages/pull/7002 the required syslinux files are located in `/usr/lib/syslinux` instead of `/usr/share/syslinux`. Updated the `SYSLINUX_DATADIR` variable to reflect these changes.
> mklive.sh: Fixed syslinux datadir value after pkg update

- mklive.sh.in
Issue in old org: https://github.com/voidlinux/void-mklive/issues/164
> mklive.sh: remove unused ISO_VOLUME variable.

- installer.sh.in
Without -f, mkfs.f2fs refuses to overwrite an existing filesystem, causing installation to fail. With this flag we match the behavior of the other filesystems.
> installer.sh.in: add -f flag to mkfs.f2fs

- Dockerfile
fix the error when no run command is specified:
```sh
$ docker run -it voidlinux/voidlinux-musl
docker: Error response from daemon: No command specified.
See 'docker run --help'.
```
> Add  /bin/dash as a default command

- Dockerfile
the busybox wget does not like our mirrors certificates for some reason
> make docker use curl

- mklive.sh.in
https://github.com/void-linux/void-mklive/pull/59
> Added the `-v` option which lets users specify the kernel version to install onto the ISO. The option takes the name of the Linux package they would like to install.
>
> Works by hijacking  `_linux_series` variable and replacing it with the user's custom Linux package. Additionally adds the user specified Linux package onto the end of the `PACKAGE_LIST` variable so it is installed into the ISO.
I did some dumb git things on my end, just easier to close the old PR and open this one
> mklive: added -v kerver option

- installer.sh.in
Right now the installer will print an error dialog but mark the filesystems done anyway and march on, which will later result in a failed GRUB installation.
> installer.sh: fail validation for EFI systems without proper ESP

- installer.sh.in
Personally, I prefer not to use `cfdisk`.
When I installed `void-linux`, I had to format the disk in advance and not use the installer for this specific step. So I had the idea to add the possibility to choose your preferred software during the installation.
> installer.sh.in: added possibility to choose partitioning software

- mkimage.sh.in
So far, image generation relied on the config shipped in the openssh
package to ensure root login with password, but as this might change in
the future, explicitly apply and document this requirement for embedded
images here instead.
The exception for GCP (disable root login) should still work as
intended.
Related: https://github.com/void-linux/void-packages/pull/17596
> mkimage.sh.in: explicitly set 'PermitRootLogin yes' in sshd_config

- mkplatformfs.sh.in
This allows replacing existing packages with custom built ones and
makes mkplatformfs behavior consistent with mkrootfs.
> Prefer repositories from '-r' in mkplatformfs

- lib.sh.in
- mkrootfs.sh.in
Call register_binfmt before installing packages on mkrootfs.
> Fix execution of post install scripts on cross builds

- mkimage.sh.in
Create boot partition starting at 32768 sectors on pinebookpro platforms. That leaves enough unallocated space to install u-boot without overlapping with any partition.
> Increase partitions shift on pinebookpro

- build-x86-images.sh.in
intel-ucode went to nonfree repository
with https://github.com/void-linux/void-packages/pull/10865
It makes more sense in permanent installations anyway
> build-x86-images.sh: remove intel-ucode from X_PKGS

- mkplatformfs.sh.in
- mkrootfs.sh.in
Instruct xbps-install to do unpack only, so packages can be properly
configured by xbps-reconfigure call.
Before, xbps-install was sometimes marking packages as configured,
thus making xbps-reconfigure call useless.
> Postpone package configuration

- Dockerfile
- Makefile
Including a copy in void-packages turned out better solution.
Grep in image don't have required perl regexps, and getting
one that have make linting slower by order of magnitude.
Even if it was already there, simply using image is
unnecessarily slower.
This reverts commit 163a923529da258d838ac6cf355aa98f3ed7b6d6.
> Dockerfile: remove spdx-licenses-list

- README.md
I'm assuming this was written in a transitional phase between systemd and runit?
> README.md: remove (presumably dated) reference to runit

- lib.sh.in
Add the magic/mask for i386 and x86_64 and register them when necessary.
Also adjust the native arch detection logic to allow (e.g.) building
aarch64* images on aarch64 without qemu installed.
> lib: register binfmts for x86, better native detection

- mklive.sh.in
On ZFS (probably btrfs, too) with compression on,
disk usage isn't the same with its real sizes.
Without "--apparent-size", du(1) will report its disk usage
which is way lower than real space needed for squashfs.
Let's ask du to provide the real apparent size for our rootfs.
--apparent-size should be available on both GNU's du (used by Void)
and BSD's du.
> du: use --apparent-size to calculate rootfs's size

- installer.sh.in
base-files's INSTALL includes some clean up that always needs to be run.
> installer: reconfigure base-files when installing.

- lib.sh.in
when building for same arch, QEMU_BIN would not be set, the condition fallsback to /usr/bin, which is executable.
rm would throw /usr/bin not empty error without causing real harm. But still nicer to handle it more gracefully.
> Check QEMU_BIN is not empty for cleanup_chroot

- lib.sh.in
Use fix binary flag (F) to load binfmt interpreter (qemu-static) on
register, so it doesn't need to be copied to chroot.
This requires kernel >= 4.9.
> Avoid copying qemu-static to rootfs

- mklive.sh.in
To help account for filesystem compression and such (particularly ZFS-on-root with compression enabled), bump the initial size reservation from (7/6) * X to 2 * X
It could probably be a bit lower, but it is probably better to avoid getting too specific to particular compression rates or filesystem optimizations.
Sponsored by: Project Trident
> Increase initial squashfs size reservation

- data/void-vpkgs.conf
- mklive.sh.in
Initial commit only removes the outdated options, I will make further commits to fix void-packages and here. Ideally this will result in complete removal of the package. I'd like to resolve this before shipping new images, having an untracked file in `/usr/share/xbps.d` is very bad.
> remove void-vpkgs

- Makefile
- lib.sh.in
- mkimage.sh.in
- mkplatformfs.sh.in
- release.sh.in
This is `[NOMERGE]` until https://github.com/void-linux/void-packages/pull/29139 is merged. 
___
1. Build packages. see:https://github.com/void-linux/void-packages/pull/29139
2. Build images
```
cd void-mklive
d=$(date '+%Y%m%d')
repo="where/your/binpkgs/are"
make XBPS_REPOSITORY="-r $repo" void-{armv6l,armv7l,aarch64}-musl-ROOTFS-$d.tar.xz void-rpi{,2,3,4}-musl-$d.img.xz
```
> Add support for split rpi kernel variants and rpi4

- installer.sh.in
The Void Linux team has switched its IRC network to libera.chat
> Change freenode.org to libera.chat

- mklive.sh.in
There are some leftovers from [now unused](https://github.com/void-linux/void-mklive/commit/77442599ced04717673e129c98ce07a015fd6bdd) [`-S`](https://github.com/void-linux/void-mklive/commit/7d89972c5756677c62d02d5f4030a97029188c0e) option. This removes the `-S` option form `getopt`.
> Fully remove unused -S option

- dracut/vmklive/adduser.sh
I think using `agetty-tty1/run` is a mistake, it does not work. After I have changed it to `agetty-tty1/conf`, it worked perfectly fine in the live image. So, I think this is the intended file!
> Fix live.autologin

- release.sh.in
REPOSITORY is only ever used as argument for `docker build` not for the Makefile
> release.sh.in: REPOSITORY should be XBPS_REPOSITORY

- dracut/autoinstaller/install.sh
- installer.sh.in
- lib.sh.in
- mklive.sh.in
Else things like efivarfs will not be passed down into the chroot,
which makes installing grub fail.
Closes #231.
> use mount --rbind to propagate mounts into the chroot

- mklive.sh.in
Fix: https://github.com/void-linux/void-mklive/issues/257
`_linux_series` will detect `linux-base` version if using `head` , it should detect the current `linux` version.
```
~ xbps-query -x linux
linux-base>=0
linux5.18>=0
```
```
~ xbps-query -p pkgname $(xbps-query -x linux|head -1)
linux-base
~ xbps-query -p pkgver $(xbps-query -x linux|head -1)
linux-base-2021.07.21_1
~ xbps-query -p pkgname $(xbps-query -x linux|tail -1)
linux5.18
~ xbps-query -p pkgver $(xbps-query -x linux|tail -1)
linux5.18-5.18.9_1
```
> fix: detect current _linux_series

- build-x86-images.sh.in
all other versions use firefox-esr, so let's also use it in the kde
image for consistency
firefox was added by @mobinmob in 33f5f5c1fb3513d2846ea637e3218f3f54d0ccd6
> build-x86-images: kde: use firefox-esr

- installer.sh.in
fixes #256
https://man.voidlinux.org/useradd#CAVEATS
matching documentation update: void-linux/void-docs#689
> installer: validate user login name based on useradd(8) rules

- build-x86-images.sh.in
* rename e to enlightenment
* enable building kde by default
* allow building multiple, but not all images (ex. -b "base xfce")
* run the script with set -e (exit when there is an error)
> build-x86-images: rewrite

- build-x86-images.sh.in
* print an error message to stderr
* exit with return code 1
> build-x86-images: fix error with missing mklive.sh

- build-x86-images.sh.in
QupZilla is no longer maintained and no longer provided in void-packages.
> build-x86-images: replace qupzilla with firefox-esr for lxqt

- installer.sh.in
this changes nothing in practice, but `sw` has no actual meaning on
Linux
<https://github.com/void-linux/void-docs/pull/693#issuecomment-1203753228>
> installer: use `defaults` mount option for swap

- mkplatformfs.sh.in
Sometimes creating the tarball can fail, so check the return code.
> fix: error detection in mkplatformfs

- dracut/autoinstaller/install.sh
Tested and confirmed bug and solution.
Added shellcheck line to say this is intentional.
> Allow multiple packages to be installed

- build-x86-images.sh.in
All other variants have their variant name in the iso file name and the base flavor is not really special. This means the iso will change its name, but the date changes with every release anyway, so it shouldn't be a big issue.
> build-x86-images: use -base suffix for the base iso

- build-x86-images.sh.in
- installer.sh.in
~~depends on: void-linux/void-packages#37826~~
see also: void-linux/void-docs#688
This will allow for easier chroot installs by way of `xchroot` and other xtools
tested a local install, and ensured that it does not include the package (previously named xtools-live, now named xtools-minimal) in the installed system:
This addition does not change the total size of the live image at all, because the xtools-live package is only ~25 KB and all dependencies are already in `base-system`
after this is merged and new live images are generated, the chroot install documentation can be updated to use `xchroot`
> [RFC] add minimal set of xtools to live images

- installer.sh.in
For f2fs, set fs_passno also to 0 if not a root filesystem. For btrfs
and xfs, set fs_passno to 0 in all cases. See fsck.btrfs(8) and
fsck.xfs(8) for more information. f2fs still seems to have issues [0].
[0] https://wiki.archlinux.org/title/F2fs#Known_issues
> installer.sh: set fs_passno to 0 for btrfs and xfs

- dracut/autoinstaller/install.sh
- dracut/vmklive/adduser.sh
- installer.sh.in
- packer/scripts/cloud.sh
- packer/scripts/vagrant.sh
`installer.sh.in` sed cannot be executed if using `(ALL)` only, because currently sudoers uses `(ALL:ALL)`.
but I'm not sure that `clouds.sh` and `vagrant.sh` need to be changed too.
> fix: sed execution for sudoers

- build-x86-images.sh.in
- installer.sh.in
The installer was originally written when the dhcpcd wpa_supplicant hook
was enabled. In early 2019, the hook was disabled and it appears that
the installer has been unable to configure WiFi since then.
To address this, enable the wpa_supplicant service, configure it, and
reload the service when dhcpcd is used for network connectivity.
Closes #5
> Enable and configure wpa_supplicant with dhcpcd

- Makefile
- lib.sh.in
- mkimage.sh.in
- mkplatformfs.sh.in
- release.sh.in
with the merge of rpi kernels, we no longer need to generate board-series-specific images
for void-linux/void-packages#39442
```
$ ls -1 void-rpi*
void-rpi-aarch64-20221001.img
void-rpi-aarch64-20221001.img.xz
void-rpi-aarch64-PLATFORMFS-20221001.tar.xz
void-rpi-aarch64-musl-20221001.img
void-rpi-aarch64-musl-20221001.img.xz
void-rpi-aarch64-musl-PLATFORMFS-20221001.tar.xz
void-rpi-armv6l-20221001.img
void-rpi-armv6l-20221001.img.xz
void-rpi-armv6l-PLATFORMFS-20221001.tar.xz
void-rpi-armv6l-musl-20221001.img
void-rpi-armv6l-musl-20221001.img.xz
void-rpi-armv6l-musl-PLATFORMFS-20221001.tar.xz
void-rpi-armv7l-20221001.img
void-rpi-armv7l-20221001.img.xz
void-rpi-armv7l-PLATFORMFS-20221001.tar.xz
void-rpi-armv7l-musl-20221001.img
void-rpi-armv7l-musl-20221001.img.xz …
```
> various: switch from rpi{,2,3,4} to rpi-$ARCH for rpi images

- lib.sh.in
Without `rslave` mounts can get stuck due to "Device or Resource Busy" errors.
> Use --make-rslave to avoid stuck mounts

- build-x86-images.sh.in
Most people probably want to use the latest non-ESR Firefox. ESR versions make sense for people who have to (or want to) stay with an older version of Firefox and still get security updates. Firefox on live isos doesn't get a security update until the package is updated, so ESR and non-ESR versions are the same in that way.
This is marked as RFC in case there is a reason why we should stay with Firefox ESR.
cc @Duncaen
> [RFC] build-x86-images: use non-ESR firefox

- dracut/autoinstaller/install.sh
visudo -c shows perms need 0440
Also w is late in the alphabet, hard to alter ordering
> autoinstaller: make wheel permission come first, fix permissions

- build-x86-images.sh.in
- mklive.sh.in
- **build-x86-images: Fix passing of additional arguments to mklive**
Mklive is called with `"$@"` to be able to pass additional arguments to it. However, since mklive is called from within a function, the value of `"$@"` is the function's argument.
This is fixed by adding `"$@"` to the function call and using shift after its first argument (the image flavour) is used.
- **mklive: Accept multiple instances of -p and -S**
This allows passing a list of packages and services to `build-x86-images.sh` without overriding its own list of packages and services passed to mklive.
> build-x86-images: fix mklive argument passtrough

- installer.sh.in
the locale default prevents an error from the second sed command
> installer: don't show groups from pkgs/live iso, default locale to C.UTF-8

- mklive.sh.in
It's possible to run mklive.sh without the -a argument in which case, the architecture is supposed to be set to the current one using xbps-uhelper. This means we have to check whether the architecture is valid after this default has been set, otherwise we get an empty string which is not a valid architecture.
> mklive.sh: check arch validity after the default is set

- installer.sh.in
- installer: use chroot instead of -R arg for useradd/chpasswd
- fixes #18
- fixes #181
- fixes #306
- installer: hide USERPASSWORD in settings
- fixes #240
- installer: default hostname to 'void' if unset
- just something i noticed along the way
> user creation omnibus

- build-x86-images.sh.in
- installer.sh.in
- build-x86-images: add xmirror
- installer: add xmirror to installation process
have to use a bit of a roundabout method because the targetdir isn't populated at the time xmirror is run. tested and works well. will set the mirror on the installed system *and* use it for the installation process 
closes #317
> add xmirror to installer/live images

- build-x86-images.sh.in
Lxdm is an old project with, the last release is from 2015 and users sometimes report lxdm giving them a black unresponsive screen after an update.
LightDM is much more maintained and much more common nowadays.
Closes: #271
Closes: #79
> build-x86-images.sh: use lightdm instead of lxdm

- installer.sh.in
fixes #131
fixes #323
This partition layout fails to install grub on the last release, but succeeds with the sorting added in this PR:
> installer.sh.in: sort filesystems by mountpoint

- installer.sh.in
regular users should not be using this group. instead, they should be using wheel and/or sudo/doas/su
> installer: hide root group in the additional groups menu

- dracut/autoinstaller/install.sh
It's nice that our stuff can be set -e but this is a regression on dracut's side that these calls are no longer safe under `set -e`.
Validated this fixes my autoinstaller problems.
Picture of a screen for the difference in call stack:
> autoinstaller: wrap dracut calls so they can error

- installer.sh.in
this well prevent needing to go through the network menu if it was already set up externally, and the user skips it before setting the source to network.
fixes #171
> installer: check for network on source selection

- installer.sh.in
This PR is a continuation of @dateiexplorer's #243, cleaned up and slightly improved, as it was too complex to rebase #243 into a coherent changeset.
closes #243
- installer.sh: fix USER*_DONE, validate user account
- installer.sh: improve network testing
- installer.sh: show_partitions: Display configured fstypes if available
- installer.sh: ensure SOURCE_DONE is accurate
- installer.sh: fix indentation of messages
> installer: various fixes for resuming installs

- build-x86-images.sh.in
- dracut/vmklive/module-setup.sh
- dracut/vmklive/screenreader.sh
- installer.sh.in
- espeakup is a screenreader for console environments
- orca is a screenreader for gui environments
they are a minimal increase to the size of the live images, but I think they are an important accessibility feature to add.
neither is enabled by default, but they are easily enabled via `ln -s /etc/sv/espeakup /var/service` or running `orca -r` (this should also be documented in void-docs eventually).
**Should these also be included in the rpi images and the various ROOTFS/PLATFORMFSes too?**
live images for testing are here: https://devspace.voidlinux.org/abby/live-a11y/
- tested on an x86_64-base image
- it might be nice to have a more convenient way to enable the service (like a `enable-espeakup` script, maybe), to minimise the chance for errors in typing the `ln` command without a …
> build-x86-images: include console screenreader

- README.md
also change the heading levels to make more sense
depends on #295
> README.md: add documentation of live iso kcl vars

- build-x86-images.sh.in
- mklive.sh.in
Running `mklive.sh` without any arguments produces a minimal image that doesn't have dialog installed which is required for installer.sh. Let's move installing the installer script up a level to `build-x86-64-images.sh` which already adds a dialog dependency.
> mklive.sh: move installer.sh to build-x86-images.sh 

- .github/workflows/gen-images.yml
- .gitignore
- Makefile
- build-x86-images.sh
- release.sh
Whether this is actually viable is currently unknown, the generated images have not been tested. an example run is [available here](https://github.com/classabbyamp/void-mklive/actions/runs/4648628064).
[images are available to test here](https://devspace.voidlinux.org/abby/live/)
- currently only manual triggering, but maybe we'd want to do this on tag/release?
- This will take probably ~2 hours to run to completion
- it would be nice to parallelise some of this, but sbc images require platformfses which require rootfses, so *some* of it has to be sequential
- also, to get everything in the same artifact, I don't think we can use `matrix` jobs
- SBC images were failing, so that hasn't been tested yet
- lots of stuff needs testing here, it was taking too long to let everything build every …
> CI for building images

- README.md
- build-x86-images.sh
- dracut/vmklive/accessibility.sh
- dracut/vmklive/module-setup.sh
- grub/grub_void.cfg.in
- installer.sh
- isolinux/isolinux.cfg.in
- mklive.sh
bootloader improvements:
- mklive: add memtest86+ to images
- closes #346 
- isolinux: add menu entries for screenreader, memtest, reboot, poweroff
- grub: add menu entries for screenreader, memtest, efi fw setup, reboot, poweroff
a11y improvements:
- dracut/vmklive: rename live.screenreader to live.accessibility
- build-x86-images.sh: add void-live-audio for a11y audio setup
- build-x86-images, dracut/vmklive, installer: add support for brltty
- build-x86-images: add orca, graphical screenreader
- closes #345 
misc:
- build-x86-images: remove duplicate line
- build-x86-images.sh: switch to pipewire on non-base images
- closes #301
> accessibility improvements, memtest86+, bootloader menu improvements

- build-x86-images.sh
> build-x86-images: show keymap selector in lightdm greeter

- mkimage.sh
This makes it easier to set up an RPi SBC image for non-MMC boot by ensuring that the right root partition is chosen. If the enumerated (sdX-style) name changes, boot can fail.
using plain UUID does not work because the kernel cannot find that itself, it would need udev/an initrd.
tested on RPi 4 with USB boot so far
> mkimage: use PARTUUID for root on rpi* images

- README.md
- mkimage.sh
> mkimage: default to 256MiB boot instead of 64MiB

- mklive.sh
- add some error handling to `umount_pseudofs`
- disable the trap before running `error_out` to stop it running multiple times
- add `--one-file-system` to ensure that the `rm -rf` can't screw you
fixes #364
> mklive.sh: fix issues with error handling and unmounting pseudofs

- mklive.sh
This adds an option to set the default shell of the `root` user and documents the `live.shell` kernel option.
I know that a similar change has already been closed (#99). My change makes this more configurable and optional. And it documents the `live.shell` option that isn't documented anywhere else and is pretty useful.
I'll understand if you close this, but I consider this helpful for people who are customizing their iso.
> Add an option to change the default shell.

- installer.sh
no reason to show these groups, and `users` is a common enough group to want to have, I think (e.g. it gives access to yubikeys)
> installer.sh: add users to default groups, ignore nogroup and chrony groups

- dracut/autoinstaller/install.sh
- dracut/autoinstaller/module-setup.sh
- dracut/autoinstaller/parse-vai-root.sh
This fixes issues where network hardware may not have settled by the time that the installer is ready to use dhclient.  It also allows the installer to claim and validate the root filesystem mount, to suppress cases where dracut is unhappy with `/dev/null`.
> dracut/autoinstaller: Fix device race conditions
