void-linux/void-mklive

mklive.sh.in

that has spaces in directory names possible.

mklive.sh: double-quote vars to make building an iso on a path

---

data/issue

see https://github.com/void-linux/xbps/commit/fcdd71aac4d9278d89cd13ec226b4e27e488f42e

data/issue: fix manpage sections for xbps utils

---

data/issue
dracut/netmenu/netmenu.sh
installer.sh.in

Someone in IRC asked for images too.

Replace mentions of voidlinux.eu

---

mkrootfs.sh.in

The -b option was mentioned in the help but wasn't implemented. Actually implemented it.

mkrootfs.sh.in: Actually implement the -b option

---

mkrootfs.sh.in

Mention ppc-musl in the list of supported architectures.

mkrootfs.sh.in: Mention ppc-musl

---

dracut/vmklive/display-manager-autologin.sh

re-enable kde images by default and fix sddm autologin config

---

installer.sh.in

Signed-off-by: Juan RP <xtraeme@gmail.com>

installer.sh.in: update my email address.

---

Dockerfile
Makefile

This is for linting license field on Travis.
One can also customize image as simple as
docker build "--build-arg=ADDINS=moreutils jq"

Dockerfile: include spdx-licenses-list

---

build-x86-images.sh.in

build-x86-images: add gnome image support

---

Makefile
lib.sh.in
mkimage.sh.in
mkplatformfs.sh.in

mkplatformfs.sh.in: Drop support for obsolete platforms

---

lib.sh.in
mkimage.sh.in
mkplatformfs.sh.in

~~Needs a void-packages PR for the base package.~~ https://github.com/void-linux/void-packages/pull/27942

Rock64 support

---

Dockerfile
Makefile
dracut/autoinstaller/autoinstall.cfg
dracut/autoinstaller/install.sh
installer.sh.in
lib.sh.in
mklive.sh.in
packer/hcl2/source-qemu.pkr.hcl
packer/hcl2/source-virtualbox-ose.pkr.hcl
packer/http/x86_64-musl.cfg

@maldridge
http -> https
alpha.de.repo.voidlinux.org -> repo-default.voidlinux.org

replace default repository URL

---

installer.sh.in

https://github.com/void-linux/void-docs/issues/692
https://github.com/void-linux/void-runit/pull/40

installer: set timezone by creating /etc/localtime symlink

---

installer.sh.in

on it's own, it's a trivial change that doesn't improve it too much, but I am using this to enable other services in another commit that I am preparing and this can be merged separately before that

installer: generalise enabling services

---

.dockerignore
hooks/README.md
hooks/build
mkimage.sh.in
mklive.sh.in
mknet.sh.in
mkplatformfs.sh.in
mkrootfs.sh.in

- .dockerignore, hooks/: remove
- mk*.sh: use UTC date
found these during developement of #331, but they don't really belong there

misc small changes

---

mkplatformfs.sh.in
mkrootfs.sh.in

things like capabilities were not being preserved
fixes #299

mkrootfs,mkplatformfs: preserve xattrs when compressing/extracting

---

README.md
mklive.sh.in

suggested in https://github.com/void-linux/void-mklive/pull/300#issuecomment-1439119162 by @0x5c

mklive.sh: allow passing multiple include dirs (-I)

---

Makefile
lib.sh
mkimage.sh
mkplatformfs.sh

see void-linux/void-packages#46493, void-linux/void-packages@6ce99104f4cfff1b5afd3a5d7b4a7f34869cc96a

*: remove support for cubie, bananapi, odroid, beaglebone, ci20 boards

---

README.md
mklive.sh

mklive: add option to ignore packages

---

lib.sh
mkimage.sh
mkplatformfs.sh

Add support for rockpro64 platform
Based on @tiemenwerkman's work on https://github.com/void-linux/void-mklive/pull/221 and comments from @CameronNemo 
Intended to be used with packages from https://github.com/void-linux/void-packages/pull/33556

Add rockpro64 to image builder

---

dracut/vmklive/module-setup.sh
dracut/vmklive/nomodeset.sh
grub/grub_void.cfg.in
installer.sh
isolinux/isolinux.cfg.in
mklive.sh

- **installer.sh: update pre-partitioning message**
- **grub, isolinux: add nomodeset menuentries, more hotkeys**
- **installer.sh: don't install/remove grub packages if bootloader is none**
- **installer.sh: put reconfigure output in a programbox**

various small fixes
